services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: flowopsai_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend-server:
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    container_name: flowopsai_backend
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      FLOWOPSAI_SERVER_PORT: ${FLOWOPSAI_SERVER_PORT}
      TRAINER_URL: http://trainer:${TRAINER_PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${FLOWOPSAI_SERVER_PORT}/api/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "${FLOWOPSAI_SERVER_PORT}:${FLOWOPSAI_SERVER_PORT}"
    volumes:
      - models_storage:/models
    restart: unless-stopped
    command: uvicorn src.server.main:app --host 0.0.0.0 --port ${FLOWOPSAI_SERVER_PORT}

  agents:
    build:
      context: ./backend
      dockerfile: Dockerfile.agents
    container_name: flowopsai_agents
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      BACKEND_URL: http://backend-server:${FLOWOPSAI_SERVER_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      postgres:
        condition: service_healthy
      backend-server:
        condition: service_started
    command: python -m src.agents.main
    volumes:
      - models_storage:/models
    restart: unless-stopped

  trainer:
    build:
      context: ./ml-trainer
      dockerfile: Dockerfile.trainer
    container_name: flowopsai_trainer
    env_file: .env
    environment:
      TRAINER_PORT: ${TRAINER_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${TRAINER_PORT}/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "${TRAINER_PORT}:${TRAINER_PORT}"
    volumes:
      - models_storage:/models
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: flowopsai_frontend
    env_file: .env
    environment:
      FLOWOPSAI_UI_PORT: ${FLOWOPSAI_UI_PORT}
      FLOWOPSAI_SERVER_PORT: ${FLOWOPSAI_SERVER_PORT}
    depends_on:
      backend-server:
        condition: service_started
      n8n:
        condition: service_started
    ports:
      - "${FLOWOPSAI_UI_PORT}:80"
    restart: unless-stopped
  n8n:
    image: n8nio/n8n:latest   # consider pinning a version later
    container_name: flowopsai_n8n
    env_file: .env
    command: start            # <— IMPORTANT: not "n8n start"
    environment:
      N8N_HOST: ${HOST}
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_PATH: /n8n/
      N8N_EDITOR_BASE_URL: http://${HOST}:${FLOWOPSAI_UI_PORT}/n8n/
      WEBHOOK_URL: http://${HOST}:${FLOWOPSAI_UI_PORT}/n8n/
      N8N_SECURE_HEADERS: false
      N8N_DISABLE_SECURE_HEADERS: true
      N8N_TRUSTED_PROXIES: '*'
      N8N_SECURE_COOKIE: 'false'
      N8N_SESSION_COOKIE_SAMESITE: lax
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_PERSONALIZATION_ENABLED: false
      N8N_PUBLIC_API_DISABLED: false
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'   # quiet the perms warning
      # If you intend to persist, either remove N8N_ENCRYPTION_KEY entirely,
      # or ensure it matches the value inside /home/node/.n8n/config
      # N8N_ENCRYPTION_KEY: <optional, see below>
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5678/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    depends_on:
      backend-server:
        condition: service_started

volumes:
  postgres_data:
  models_storage:
  n8n_data:
