version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    container_name: flowopsai-backend
    env_file:
      - .env
    command: uvicorn src.server.main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "${FLOWOPSAI_SERVER_PORT}:5000"
    depends_on:
      - db
    networks:
      - flowopsai-net
    restart: unless-stopped

  agents:
    build:
      context: ./backend
      dockerfile: Dockerfile.agents
    container_name: flowopsai-agents
    env_file:
      - .env
    command: python src/agents/main.py
    ports:
      - "${FLOWOPSAI_AGENTS_PORT}:8052"
    depends_on:
      - backend
    networks:
      - flowopsai-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: flowopsai-frontend
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - VITE_API_URL=http://backend:5000
      - VITE_TRAINER_URL=http://ml-trainer:8090
    ports:
      - "${FLOWOPSAI_UI_PORT}:5173"
    depends_on:
      - backend
    networks:
      - flowopsai-net
    restart: unless-stopped

  ml-trainer:
    build:
      context: ./ml-trainer
      dockerfile: Dockerfile.trainer
    container_name: flowopsai-ml-trainer
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 8090
    ports:
      - "${TRAINER_PORT}:8090"
    volumes:
      - ./ml-trainer/data:/app/data
      - ./ml-trainer/models:/app/models
    networks:
      - flowopsai-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "python - <<'PY'\nimport urllib.request;urllib.request.urlopen('http://localhost:8090/').read()\nPY"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  db:
    image: postgres:15
    container_name: flowopsai-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flowopsai-net

networks:
  flowopsai-net:

volumes:
  postgres_data:
